dist: trusty

os: linux
language: python

install:
    - bash bin/travis-build.bash
services:
    - redis
    - postgresql

script: bash bin/travis-run.bash
before_install:
    - pip install codecov
after_success:
    - codecov

jobs:
  include:
    - stage: Flake8
      python: 2.7
      env: FLAKE8=True
      install:
        - pip install flake8==3.5.0
        - pip install pycodestyle==2.3.0
      script:
        - flake8 --version
        - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan
    - stage: Tests
      python: "2.7"
      env: CKANVERSION=master
    - python: "3.6"
      env: CKANVERSION=master

cache:
  directories:
    - $HOME/.cache/pip
