[tool.black]
line-length = 79

[tool.towncrier]
directory = "changes"
package = "ckanext.workflow"
package_dir = "ckanext/workflow"
filename = "CHANGELOG.rst"
title_format = "{version} ({project_date})"
issue_format = "{issue}"

[[tool.towncrier.type]]
directory = "removal"
name = "Deprecations and removals"
showcontent = true
